name: boilerplate
description: A new Flutter project.
publish_to: 'none'


version: 1.1.0+2

environment:
  sdk: ">=2.19.0 <3.11.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.7.0
  flutter_mobx: ^2.0.6+4
  supabase_flutter: ^1.0.0
  mobx: ^2.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get_it: ^7.2.0
  injectable: ^2.1.0
  easy_localization: ^3.0.1
  logger: ^1.1.0
  flutter_svg: ^2.0.5
  ionicons: ^0.2.1
  google_fonts: ^4.0.3
  auto_route: ^6.3.0
  flutter_secure_storage: ^8.0.0
  lottie: ^2.0.0
  file_picker: ^5.2.2
  flutter_webrtc: ^0.9.11
  peerdart: 0.5.0
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.1
  equatable: ^2.0.5
  flutter_native_splash: ^2.2.16
  adaptive_dialog: ^1.8.0+1
  unique_name_generator: 1.0.0
  envied: ^0.3.0
  uuid: ^3.0.7
  auto_size_text: ^3.0.0
  path_provider: ^2.0.11
  introduction_screen: ^3.1.1
  responsive_framework: ^1.0.0


dev_dependencies:
  build_runner: ^2.3.3
  very_good_analysis: ^4.0.0+1
  mobx_codegen: ^2.2.0
  hive_generator: ^2.0.0
  injectable_generator: ^2.1.5
  auto_route_generator: ^6.2.0
  flutter_gen_runner: ^5.3.0
  envied_generator: ^0.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/animations/


flutter_gen:
  output: lib/generated/
  line_length: 80

  # Optional
  integrations:
    flutter_svg: true
    lottie: true
