name: boilerplate
description: A new Flutter project.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.2
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0

dev_dependencies:
  build_runner: ^2.2.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.1
  json_serializable: ^6.4.1
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true