name: boilerplate
description: A new Flutter project.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.7.0
  flutter_mobx: ^2.0.6+4
  supabase_flutter: ^1.0.0
  mobx: ^2.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get_it: ^7.2.0
  injectable: ^1.5.3
  easy_localization: ^3.0.1
  logger: ^1.1.0
  flutter_svg: ^1.1.5
  ionicons: ^0.2.1
  google_fonts: ^3.0.1
  auto_route: ^5.0.2
  flutter_gen: ^5.0.3
  flutter_secure_storage: 6.1.0-beta.1
  lottie: ^1.4.3
  file_picker: ^5.2.2
  flutter_webrtc: ^0.9.11
  peerdart: 0.4.0-beta.4
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.1
  equatable: ^2.0.5
  flutter_native_splash: ^2.2.12


dev_dependencies:
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.1.0
  mobx_codegen:
    git:
      url: https://github.com/amondnet/mobx.dart.git
      path: mobx_codegen
      ref: analyzer-4.4.0
  hive_generator: ^2.0.0
  injectable_generator: 
    git:
      url: https://github.com/amondnet/injectable.git
      path: injectable_generator
  auto_route_generator: ^5.0.2
  flutter_gen_runner: ^5.0.0
  envied_generator:
    git: 
      url: https://github.com/daiki1003/envied.git
      path: packages/envied_generator
      ref: migrate/analyzer_5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/animations/


flutter_gen:
  output: lib/generated/
  line_length: 80

  # Optional
  integrations:
    flutter_svg: true
    lottie: true
