name: boilerplate
description: A new Flutter project.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0
  go_router: ^5.0.5
  dio: ^4.0.6
  flutter_mobx: ^2.0.6+4
  mobx: ^2.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get_it: ^7.2.0
  injectable: ^1.5.3
  easy_localization: ^3.0.1


dev_dependencies:
  build_runner: ^2.2.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.4.1
  very_good_analysis: ^3.1.0
  mobx_codegen: ^2.0.7+3
  hive_generator: ^1.1.3
  injectable_generator: ^1.5.4

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
